### ISSUE TITLE
Comentario avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [EAlejandra/ProyectoFinalBioinf2017-II#1]
Se ve interesante tu proyecto, pero me gustaría que aclararas, en el documento del avance 1, lo siguiente: ¿qué tipos de análisis realizarás exactamente? ¿en qué formato te llegarán estos datos y cuándo? ¿tienes en mente que software/paquetes utilizarás para los análisis?

**Comment by EAlejandra** [comment]
ya modifique el archivo avance 1

**Comment by AliciaMstt** [comment]
Recuerda que el pre-procesamiento es cuando tienes datos crudos, es decir secuencias fastqc que filtrar por calidad. En tu caso si ya tienes datos bam no será necesario realizar ningún pre-procesamiento, sino pasar directo a los análisis.

En tu avance 2 ya tienes que tener definido qué software ocuparás, haberlo logrado instalar y especificar qué funciones en específico utilizarás para hacer qué. Yo te recomendaría que empezaras por darle un ojo a SAMtools

http://www.htslib.org/
