### ISSUE TITLE
Comentarios avance 2

### ISSUE THREAD

**Issue by AliciaMstt** [EAlejandra/ProyectoFinalBioinf2017-II#2]
Muy bien. 

Sólo no me queda claro si ya instalaste SAMTools (el git clone no es instalarlo, solo bajarlo). Por favor especifica esto e instálalo, en caso de que no lo hayas instalado ya.

**Comment by EAlejandra** [comment]
No lo he instalado, pero a la brevedad lo instalaré

**Comment by AliciaMstt** [comment]
Necesito que antes de tu avance 3 ya tengas instalado SAMTools.

**Comment by EAlejandra** [comment]
Ok, trabajare en eso. 
Saludos
