### ISSUE TITLE
comentarios avances 3

### ISSUE THREAD

**Issue by AliciaMstt** [EAlejandra/ProyectoFinalBioinf2017-II#3]
Veo que a la fecha del envío de tu avance 3 aún no tenías datos. Me preocupa que tengas que hacer todo en una semana. 

Tu curl no corre porque pusiste mal la dirección, revisa el ejemplo de la unidad 2 y compara con o de abajo. Busca la diferencia:

`curl -s "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&rettype=fasta&id=179033,206725550,23491728,1518793,1732377" > secuenciasreferencia`

**Comment by EAlejandra** [comment]
Ya vi cual fue el error, lo corregí y si pude bajar todas las secuencias
